name: Shirodo-Queue
author: Shirodo
description: Queue plugin for my own server.
main: me.shirodo.queue.ShirodoQueue
version: 1.3
api-version: 1.16
commands:
    list:
        description: Siradaki uyelerin listesini alir